spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: 'TRUE'
        hibernate:
            ddl-auto: update
        open-in-view: 'false'
    sql:
        init:
            mode: never
    mvc:
        hiddenmethod:
            filter:
                enabled: 'true'
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        username: root
        url: jdbc:mysql://localhost:3306/home_delivery?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor: TRACE
                SQL: DEBUG
            nodeValue: WARN
        blog: WARN
server:
    port: 8080

mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true
                    required: true
                ssl:
                    trust: smtp.gmail.com

