spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodavalnik?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  port: 8080

suppliers:
  api:
    baseUrl: "${OFFERS_BASE_URL:http://localhost:8081}"

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:your-email@gmail.com}
  password: ${MAIL_PASSWORD:your-email-password}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        ssl:
          trust: smtp.gmail.com
