INSERT INTO offers (description, image_url, name, price, category_id, shop_id) VALUES
("Comfortable cotton t-shirt.", "/images/clothes/t_shirt.jpg", "Cotton T-shirt", 10.00, 1, 1),
("Stylish leather jacket.", "/images/clothes/jacket.jpg", "Leather Jacket", 150.00, 1, 2),
("Casual denim jeans.", "/images/clothes/jeans.jpg", "Denim Jeans", 40.00, 1, 3),
("Smartphone with high-resolution camera.", "/images/electronics/smartphone.jpeg", "Smartphone", 300.00, 2, 1),
("Laptop with 16GB RAM and 512GB SSD.", "/images/electronics/macbook.jpg", "Laptop", 1200.00, 2, 2),
("Wireless noise-cancelling headphones.", "/images/electronics/headphones.jpg", "Headphones", 200.00, 2, 3),
("Ergonomic office chair.", "/images/furniture/chair.jpg", "Office Chair", 100.00, 3, 1),
("Modern wooden dining table.", "/images/furniture/table.jpg", "Dining Table", 500.00, 3, 2),
("Comfortable queen-size bed.", "/images/furniture/bed.jpg", "Queen-size Bed", 800.00, 3, 3),
("Classic wool sweater.", "/images/clothes/wool.jpg", "Wool Sweater", 50.00, 1, 1),
("Elegant evening dress.", "/images/clothes/dress.jpg", "Evening Dress", 120.00, 1, 2),
("4K Ultra HD Smart TV.", "/images/electronics/tv.jpg", "Smart TV", 600.00, 2, 3),
("Solid oak wardrobe.", "/images/furniture/oak.jpg", "Oak Wardrobe", 700.00, 3, 1),
("Comfortable running shoes.", "/images/clothes/shoes.jpg", "Running Shoes", 80.00, 1, 2),
("Bluetooth portable speaker.", "/images/electronics/speaker.jpg", "Portable Speaker", 50.00, 2, 3),
("Luxury leather sofa.", "/images/furniture/sofa.jpg", "Leather Sofa", 1000.00, 3, 1);
